//
// Created by hd on 1/10/18.
//
#include <ros/package.h>
#include <message_filters/subscriber.h>
#include <message_filters/synchronizer.h>
#include <message_filters/sync_policies/approximate_time.h>
#include "map_add.h"

using namespace std;
using namespace message_filters;

int main(int argc, char** argv) {
    ros::init(argc, argv, "cmerge_node");

    ros::NodeHandle n_private("~");
    ros::NodeHandle nh;

    // obstacle individual merge
    obstacle_ind_merge *mpObstacle_ind_merge;

    // obstacles merge
    Obstacle_merge *mpObstacle_merge;

    MapPublisher *mpMapPublisher;

    mpObstacle_merge = new Obstacle_merge();

    mpObstacle_ind_merge = new obstacle_ind_merge(mpObstacle_merge);

    mpMapPublisher = new MapPublisher(nh, n_private, mpObstacle_ind_merge, mpObstacle_merge);

    MapAdd mapAdd(n_private, mpObstacle_ind_merge, mpObstacle_merge, mpMapPublisher, 0);

    double time_diff;

    string pose_topic, map_topic, map_topic_2;

//    pose_topic = "/ugv_slam_node/posestamped";
    pose_topic = "/gps_aligned/pose";
    map_topic_2 = "/long/map_msg";
    map_topic = "/wide/map_msg";

    time_diff = 0.4;

    if (n_private.getParam("topic/pose", pose_topic)) {
        ROS_WARN("Pose Info Subscribing to: %s", pose_topic.c_str());
    }

    if (n_private.getParam("topic/map_wide", map_topic)) {
        ROS_WARN("Cam Map Info Subscribing to: %s", map_topic.c_str());
    }

    if (n_private.getParam("topic/map_long", map_topic_2)) {
        ROS_WARN("Additional Cam Map Info Subscribing to: %s", map_topic_2.c_str());
    }

    if (n_private.getParam("topic/time_diff", time_diff)) {
        ROS_WARN("Time difference is set to: %f", time_diff);
    }

    ROS_WARN("now begin to subscribe to the map...");


    //////Only for debugging!//////
//    ros::Subscriber gps_sub, map_sub;
//
//    gps_sub = nh.subscribe(pose_topic, 40, &MapAdd::gps_callback, &mapAdd);
//
//    map_sub = nh.subscribe(map_topic_2, 20, &MapAdd::map_callback, &mapAdd);

    //////Only for debugging!//////



    ///*********Subscribe to pose and two sources of maps! *************//

    Subscriber<geometry_msgs::PoseWithCovarianceStamped> pose_sub(nh, pose_topic, 20);

    Subscriber<obstacle_msgs::MapInfo> map_sub_wide(nh, map_topic,5);

    Subscriber<obstacle_msgs::MapInfo> map_sub_long(nh, map_topic_2, 5);

    typedef sync_policies::ApproximateTime<geometry_msgs::PoseWithCovarianceStamped, obstacle_msgs::MapInfo,
            obstacle_msgs::MapInfo> SyncPolicy;         //Map generated by wide cam set first, long set second!

    Synchronizer<SyncPolicy> sync(SyncPolicy(20), pose_sub, map_sub_wide, map_sub_long);

    sync.setMaxIntervalDuration(ros::Duration(time_diff));

    sync.registerCallback(boost::bind(&MapAdd::addMapInfo, &mapAdd, _1, _2, _3));

    ///*********Subscribe to pose and two sources of maps! *************//



    ///*********Subscribe to pose and 1 source of maps! ****************//

//    cout << "now subscribing to one map..." << endl;
//
//    Subscriber<geometry_msgs::PoseWithCovarianceStamped> pose_sub(nh, pose_topic, 20);
//
//    Subscriber<obstacle_msgs::MapInfo> map_sub(nh, map_topic_2, 5);
//
//    typedef sync_policies::ApproximateTime<geometry_msgs::PoseWithCovarianceStamped, obstacle_msgs::MapInfo> SyncPolicy;
//
//    Synchronizer<SyncPolicy> sync(SyncPolicy(10), pose_sub, map_sub);
//
//    sync.setMaxIntervalDuration(ros::Duration(time_diff));
//
//    sync.registerCallback(boost::bind(&MapAdd::addMapSingle, &mapAdd, _1, _2));



    ros::spin();

    return 0;
}
